"""
FIELD_SCHEMA — Single source of truth for all 163 company intelligence fields.

Each entry defines:
  - type: currency | percentage | year | integer | rating_5 | string | text | boolean
  - nullable: True if the field may legitimately be null; False if always required
"""

FIELD_SCHEMA: dict[str, dict] = {
    # ── Overview ──────────────────────────────────────────────────────────────
    "name":                       {"type": "string",     "nullable": False},
    "short_name":                 {"type": "string",     "nullable": True},
    "logo_url":                   {"type": "string",     "nullable": True},
    "category":                   {"type": "string",     "nullable": True},
    "industry":                   {"type": "string",     "nullable": True},
    "incorporation_year":         {"type": "year",       "nullable": True},
    "overview_text":              {"type": "text",       "nullable": True},
    "nature_of_company":          {"type": "string",     "nullable": True},
    "headquarters_address":       {"type": "string",     "nullable": True},
    "operating_countries":        {"type": "text",       "nullable": True},
    "office_count":               {"type": "integer",    "nullable": True},
    "office_locations":           {"type": "text",       "nullable": True},
    "vision_statement":           {"type": "text",       "nullable": True},
    "mission_statement":          {"type": "text",       "nullable": True},
    "core_values":                {"type": "text",       "nullable": True},
    "history_timeline":           {"type": "text",       "nullable": True},
    "recent_news":                {"type": "text",       "nullable": True},
    "website_url":                {"type": "string",     "nullable": True},
    "linkedin_url":               {"type": "string",     "nullable": True},
    "twitter_handle":             {"type": "string",     "nullable": True},
    "facebook_url":               {"type": "string",     "nullable": True},
    "instagram_url":              {"type": "string",     "nullable": True},
    "primary_contact_email":      {"type": "string",     "nullable": True},
    "primary_phone_number":       {"type": "string",     "nullable": True},
    "marketing_video_url":        {"type": "string",     "nullable": True},
    "customer_testimonials":      {"type": "text",       "nullable": True},
    "website_quality":            {"type": "text",       "nullable": True},
    "website_rating":             {"type": "rating_5",   "nullable": True},
    "website_traffic_rank":       {"type": "integer",    "nullable": True},
    "social_media_followers":     {"type": "integer",    "nullable": True},
    "awards_recognitions":        {"type": "text",       "nullable": True},
    "brand_sentiment_score":      {"type": "rating_5",   "nullable": True},
    "event_participation":        {"type": "text",       "nullable": True},
    "pain_points_addressed":      {"type": "text",       "nullable": True},
    "focus_sectors":              {"type": "text",       "nullable": True},
    "offerings_description":      {"type": "text",       "nullable": True},
    "top_customers":              {"type": "text",       "nullable": True},
    "core_value_proposition":     {"type": "text",       "nullable": True},
    "unique_differentiators":     {"type": "text",       "nullable": True},
    "competitive_advantages":     {"type": "text",       "nullable": True},
    "weaknesses_gaps":            {"type": "text",       "nullable": True},
    "key_challenges_needs":       {"type": "text",       "nullable": True},
    "key_competitors":            {"type": "text",       "nullable": True},
    "market_share_percentage":    {"type": "percentage", "nullable": True},
    "sales_motion":               {"type": "text",       "nullable": True},
    "benchmark_vs_peers":         {"type": "text",       "nullable": True},
    "future_projections":         {"type": "text",       "nullable": True},
    "strategic_priorities":       {"type": "text",       "nullable": True},
    "industry_associations":      {"type": "text",       "nullable": True},
    "case_studies":               {"type": "text",       "nullable": True},
    "go_to_market_strategy":      {"type": "text",       "nullable": True},
    "innovation_roadmap":         {"type": "text",       "nullable": True},
    "product_pipeline":           {"type": "text",       "nullable": True},
    "tam":                        {"type": "currency",   "nullable": True},
    "sam":                        {"type": "currency",   "nullable": True},
    "som":                        {"type": "currency",   "nullable": True},

    # ── Culture ───────────────────────────────────────────────────────────────
    "employee_size":              {"type": "integer",    "nullable": True},
    "glassdoor_rating":           {"type": "rating_5",   "nullable": True},
    "indeed_rating":              {"type": "rating_5",   "nullable": True},
    "google_rating":              {"type": "rating_5",   "nullable": True},
    "leave_policy":               {"type": "text",       "nullable": True},
    "health_support":             {"type": "text",       "nullable": True},
    "fixed_vs_variable_pay":      {"type": "text",       "nullable": True},
    "bonus_predictability":       {"type": "text",       "nullable": True},
    "esops_incentives":           {"type": "text",       "nullable": True},
    "family_health_insurance":    {"type": "text",       "nullable": True},
    "relocation_support":         {"type": "text",       "nullable": True},
    "lifestyle_benefits":         {"type": "text",       "nullable": True},
    "hiring_velocity":            {"type": "text",       "nullable": True},
    "employee_turnover":          {"type": "percentage", "nullable": True},
    "avg_retention_tenure":       {"type": "string",     "nullable": True},
    "diversity_metrics":          {"type": "text",       "nullable": True},
    "work_culture_summary":       {"type": "text",       "nullable": True},
    "manager_quality":            {"type": "text",       "nullable": True},
    "psychological_safety":       {"type": "text",       "nullable": True},
    "feedback_culture":           {"type": "text",       "nullable": True},
    "diversity_inclusion_score":  {"type": "rating_5",   "nullable": True},
    "ethical_standards":          {"type": "text",       "nullable": True},
    "burnout_risk":               {"type": "text",       "nullable": True},
    "layoff_history":             {"type": "text",       "nullable": True},
    "mission_clarity":            {"type": "text",       "nullable": True},
    "sustainability_csr":         {"type": "text",       "nullable": True},
    "crisis_behavior":            {"type": "text",       "nullable": True},
    "remote_policy_details":      {"type": "text",       "nullable": True},
    "typical_hours":              {"type": "string",     "nullable": True},
    "overtime_expectations":      {"type": "text",       "nullable": True},
    "weekend_work":               {"type": "text",       "nullable": True},
    "flexibility_level":          {"type": "text",       "nullable": True},
    "location_centrality":        {"type": "text",       "nullable": True},
    "public_transport_access":    {"type": "text",       "nullable": True},
    "cab_policy":                 {"type": "text",       "nullable": True},
    "airport_commute_time":       {"type": "string",     "nullable": True},
    "office_zone_type":           {"type": "string",     "nullable": True},
    "area_safety":                {"type": "text",       "nullable": True},
    "safety_policies":            {"type": "text",       "nullable": True},
    "infrastructure_safety":      {"type": "text",       "nullable": True},
    "emergency_preparedness":     {"type": "text",       "nullable": True},
    "training_spend":             {"type": "currency",   "nullable": True},
    "onboarding_quality":         {"type": "text",       "nullable": True},
    "learning_culture":           {"type": "text",       "nullable": True},
    "exposure_quality":           {"type": "text",       "nullable": True},
    "mentorship_availability":    {"type": "text",       "nullable": True},
    "internal_mobility":          {"type": "text",       "nullable": True},
    "promotion_clarity":          {"type": "text",       "nullable": True},
    "tools_access":               {"type": "text",       "nullable": True},
    "role_clarity":               {"type": "text",       "nullable": True},
    "early_ownership":            {"type": "text",       "nullable": True},
    "work_impact":                {"type": "text",       "nullable": True},
    "execution_thinking_balance": {"type": "text",       "nullable": True},
    "automation_level":           {"type": "text",       "nullable": True},
    "cross_functional_exposure":  {"type": "text",       "nullable": True},
    "exit_opportunities":         {"type": "text",       "nullable": True},
    "skill_relevance":            {"type": "text",       "nullable": True},
    "external_recognition":       {"type": "text",       "nullable": True},
    "network_strength":           {"type": "text",       "nullable": True},
    "global_exposure":            {"type": "text",       "nullable": True},

    # ── Financials ────────────────────────────────────────────────────────────
    "annual_revenue":             {"type": "currency",   "nullable": True},
    "annual_profit":              {"type": "currency",   "nullable": True},
    "revenue_mix":                {"type": "text",       "nullable": True},
    "valuation":                  {"type": "currency",   "nullable": True},
    "yoy_growth_rate":            {"type": "percentage", "nullable": True},
    "profitability_status":       {"type": "string",     "nullable": True},
    "key_investors":              {"type": "text",       "nullable": True},
    "recent_funding_rounds":      {"type": "text",       "nullable": True},
    "total_capital_raised":       {"type": "currency",   "nullable": True},
    "customer_acquisition_cost":  {"type": "currency",   "nullable": True},
    "customer_lifetime_value":    {"type": "currency",   "nullable": True},
    "cac_ltv_ratio":              {"type": "string",     "nullable": True},
    "churn_rate":                 {"type": "percentage", "nullable": True},
    "net_promoter_score":         {"type": "string",     "nullable": True},  # NPS: -100–100, kept as string
    "burn_rate":                  {"type": "currency",   "nullable": True},
    "runway_months":              {"type": "integer",    "nullable": True},
    "burn_multiplier":            {"type": "string",     "nullable": True},
    "regulatory_status":          {"type": "text",       "nullable": True},
    "legal_issues":               {"type": "text",       "nullable": True},
    "esg_ratings":                {"type": "string",     "nullable": True},
    "supply_chain_dependencies":  {"type": "text",       "nullable": True},
    "geopolitical_risks":         {"type": "text",       "nullable": True},
    "macro_risks":                {"type": "text",       "nullable": True},
    "carbon_footprint":           {"type": "text",       "nullable": True},
    "ethical_sourcing":           {"type": "text",       "nullable": True},
    "customer_concentration_risk":{"type": "text",       "nullable": True},
    "exit_strategy_history":      {"type": "text",       "nullable": True},
    "ceo_name":                   {"type": "string",     "nullable": True},
    "ceo_linkedin_url":           {"type": "string",     "nullable": True},
    "key_leaders":                {"type": "text",       "nullable": True},
    "warm_intro_pathways":        {"type": "text",       "nullable": True},
    "decision_maker_access":      {"type": "text",       "nullable": True},
    "contact_person_name":        {"type": "string",     "nullable": True},
    "contact_person_title":       {"type": "string",     "nullable": True},
    "contact_person_email":       {"type": "string",     "nullable": True},
    "contact_person_phone":       {"type": "string",     "nullable": True},
    "board_members":              {"type": "text",       "nullable": True},
    "company_maturity":           {"type": "string",     "nullable": True},
    "brand_value":                {"type": "currency",   "nullable": True},
    "client_quality":             {"type": "text",       "nullable": True},
    "technology_partners":        {"type": "text",       "nullable": True},
    "intellectual_property":      {"type": "text",       "nullable": True},
    "r_and_d_investment":         {"type": "currency",   "nullable": True},
    "ai_ml_adoption_level":       {"type": "text",       "nullable": True},
    "tech_stack":                 {"type": "text",       "nullable": True},
    "cybersecurity_posture":      {"type": "text",       "nullable": True},
    "partnership_ecosystem":      {"type": "text",       "nullable": True},
    "tech_adoption_rating":       {"type": "rating_5",   "nullable": True},
}

# Derived helpers
NUMERIC_TYPES = {"currency", "percentage", "year", "integer", "rating_5"}
RETRYABLE_TYPES = {"currency", "percentage", "year", "integer", "rating_5"}

def get_field_type(field_name: str) -> str:
    return FIELD_SCHEMA.get(field_name, {}).get("type", "string")

def is_nullable(field_name: str) -> bool:
    return FIELD_SCHEMA.get(field_name, {}).get("nullable", True)

def is_retryable(field_name: str) -> bool:
    """Return True if a null value for this field should trigger a retry."""
    schema = FIELD_SCHEMA.get(field_name, {})
    # Always retry non-nullable nulls; also retry structured numeric nulls
    if not schema.get("nullable", True):
        return True
    return schema.get("type", "string") in RETRYABLE_TYPES
